# Generated by Django 4.2.4 on 2023-08-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='size',
            field=models.CharField(choices=[('230', '230'), ('240', '240'), ('250', '250'), ('260', '260'), ('270', '270')], max_length=10, verbose_name='Size'),
        ),
    ]
