# Generated by Django 4.2.4 on 2023-08-21 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '주문임', 'verbose_name_plural': '주문임'},
        ),
    ]
